apiVersion: v1
kind: Service
metadata:
  name: springboot1-k8s
  labels:
    name: springboot1-k8s
spec:
  ports:
    - nodePort: 30163 
      port: 8080      
      targetPort: 8080  
      protocol: TCP
  selector:           
    app: springboot1-k8s
  type: NodePort       

